
name = "DongjakDashComponents2"
uuid = "1b08a953-4be3-4667-9a23-7451b0f3afa8"
authors = ["cruldra <cruldra@gmail.com>"]
version = "0.0.39"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
