.dongjakDashComponents2_js_metadata <- function() {
deps_metadata <- list(`dongjak_dash_components2` = structure(list(name = "dongjak_dash_components2",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DongjakDashComponents2.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dongjakDashComponents2",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dongjak_dash_components2` = structure(list(name = "dongjak_dash_components2",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DongjakDashComponents2.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dongjakDashComponents2",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dongjak_dash_components2` = structure(list(name = "dongjak_dash_components2",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dongjak_dash_components2.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dongjakDashComponents2",
all_files = FALSE), class = "html_dependency"),
`dongjak_dash_components2` = structure(list(name = "dongjak_dash_components2",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dongjak_dash_components2.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dongjakDashComponents2",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
